<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app-icon.ico</ApplicationIcon>
    <Version>1.1.2</Version>
    <AssemblyVersion>1.1.2.0</AssemblyVersion>
    <FileVersion>1.1.2.0</FileVersion>
    <Product>Phasmo Hunt</Product>
    <Authors>JJuniorS</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app-icon.png" />
    <Resource Include="Assets\en.png" />
    <Resource Include="Assets\pt-Br.png" />
    <Resource Include="Assets\Evidence\*.png" />
    <Resource Include="Assets\Peculiarities\*.png" />
  </ItemGroup>

</Project>
